name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  equatable: ^2.0.5
  cloud_firestore: ^5.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
